### PR TITLE
Solution for problem 20 Python

### PR DESCRIPTION
**Pull request by danielalbinoms**
Ahí les encargo

### CODE REVIEW

**Review by Bydel93 — APPROVED** [review]
LGTM 💯

**Review by alnavarroh — APPROVED** [review]
nice job ✅

**Review by Eduardo-93 — APPROVED** [review]

**Review by alnavarroh — CHANGES_REQUESTED** [review]
pls remove pycache directory

**Review by Darova93 — APPROVED** [review]

**Review by alnavarroh — APPROVED** [review]
confirmo

**Pull request merged**
